import = [
    "~/.config/alacritty/themes/themes/gruvbox_hard.toml"
]

[window]
    padding = { x = 8, y = 8 }
    opacity = 0.95

[font]
    normal = { family = "JetBrains Mono", style = "Regular" }
    size   = 14
